# This file was generated by GoReleaser. DO NOT EDIT.
cask "synapse" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "52fe41970a84f13fbd30f25c66c8b27aee90d02a0fca3fa315bf4acfa8a4568c"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7b925a3b8124506e5e16b4bf527a42c22d49d675ba807353d73b63f763fc553f"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8119986574824bbb2f122fc637d3d9fd5214d286dc16d98c3f0a9aa7e7940544"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94011ed6d086838f60d1c130bcc81e72d4d7d6c3df2be27deb90b7ebd7d249ae"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synapse"
  desc "Semantic vector search for Engram memory — pure Go, MCP-native."
  homepage "https://github.com/000Erick/synapse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synapse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synapse"]
    end
  end

  # No zap stanza required

end
