# This file was generated by GoReleaser. DO NOT EDIT.
cask "synapse" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f833a9080d7cbe42ab6ab10170e0dbeecb7513a1d8853a0d3c954ab902d60cef"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "26c68b4927ffd9a2fb434b76e5421fbdd78f252afdcde347d071618939f07bd1"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "85278a383416ce726bbd6c47f83313430acdb4640685a2c744a7790ee4a346e2"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "931f40265a284e4e8ee74f2533c54f2a8db3b5e7a34425eefa7add3d34ecbf8d"
      url "https://github.com/000Erick/synapse/releases/download/v#{version}/synapse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "synapse"
  desc "Semantic vector search for Engram memory — pure Go, MCP-native."
  homepage "https://github.com/000Erick/synapse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "synapse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/synapse"]
    end
  end

  # No zap stanza required

end
